Find sine value of PI/2:

In [1]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


Find sine values for all of the values in arr:

In [2]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


Convert all of the values in following array arr to radians:

In [3]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


Convert all of the values in following array arr to degrees:

In [4]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


Find the angle of 1.0:

In [5]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966



Find the angle for all of the sine values in the array

In [6]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


Find the hypotenues for 4 base and 3 perpendicular:

In [7]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
