Generate a random integer from 0 to 100:

In [1]:
from numpy import random

x = random.randint(100)

print(x)

84


Generate a random float from 0 to 1:

In [2]:
from numpy import random

x = random.rand()

print(x)

0.4045402385614495


Generate a 1-D array containing 5 random integers from 0 to 100:

In [3]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[53 42 16 51 91]


Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [4]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[44 18 29 53 53]
 [51 29 76  8  3]
 [94 48 47  7 63]]


Generate a 1-D array containing 5 random floats:

In [5]:
from numpy import random

x = random.rand(5)

print(x)

[0.13213912 0.32886387 0.84521384 0.28461194 0.84305864]


Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [6]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.22188319 0.59948799 0.704694   0.31009219 0.55510602]
 [0.02300625 0.51029087 0.30060688 0.21929116 0.42153247]
 [0.16612623 0.71891473 0.31297622 0.21961535 0.46317544]]


Return one of the values in an array:

In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 9 9 7 7]
 [5 7 9 9 7]
 [9 5 5 9 3]]
